name: Package and release

on:
    push:
        tags:
            - "*"

jobs:
    release:
        permissions: write-all
        runs-on: ubuntu-latest
        env:
            GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
            CF_API_KEY: ${{ secrets.CF_API_KEY }}
            WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

        steps:
          - name: Clone project
            uses: actions/checkout@v4

          - name: Package and release
            uses: BigWigsMods/packager@v2
